update github actions

diff --git a/.github/workflows/Render-README.yaml b/.github/workflows/Render-README.yaml
--- a/.github/workflows/Render-README.yaml
+++ b/.github/workflows/Render-README.yaml
@@ -1,33 +1,36 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    paths:
-      - README.Rmd
+    paths: ['**.Rmd']
 
-name: Render README
+name: render-rmarkdown
 
 jobs:
-  render:
-    name: Render README
-    runs-on: macOS-latest
-
+  render-rmarkdown:
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout repo
+        uses: actions/checkout@v2
         with:
-          token: ${{ secrets.PAT }}
-      - uses: r-lib/actions/setup-r@master
-      - uses: r-lib/actions/setup-pandoc@master
-    
-      - name: Install dependencies
+          fetch-depth: 0
+
+      - uses: r-lib/actions/setup-pandoc@v2
+
+      - uses: r-lib/actions/setup-r@v2
+
+      - uses: r-lib/actions/setup-renv@v2
+      
+      - name: Render Rmarkdown files
         run: |
-          install.packages(c('rmarkdown', 'svglite', 'showtext', 'devtools'))
-          devtools::install_deps()
-        shell: Rscript {0}
-    
-      - name: Render README
-        run: rmarkdown::render('README.Rmd')
-        shell: Rscript {0}
-    
+          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
+          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
+
       - name: Commit results
         run: |
-          git commit README.md man/figures -m 'Re-build README.Rmd' || echo 'No changes to commit'
-          git push origin || echo 'No changes to commit'
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
+          git push origin || echo "No changes to commit"
